---
  language: ruby

  os:
    - linux

  services: 
    - docker

  dist: bionic

  before_install:
    - docker pull pipseed/ansible-molecule:18.04

  script:
    - ansible-playbook tests/test.yml -i test/inventory --syntax-check