---
# Hardening section for Docker on Ubuntu 18.04
- name: "| 3.1 | Ensure that the docker.service file ownership is root:root | Scored"
  file: 
    path: /lib/systemd/system/docker.service
    owner: root
    group: root
  tags:
    - level1_host
    - scored
    - rule_3.1

- name: "| 3.2 | Ensure that docker.service file permissions are set to 644 | Scored"
  file: 
    path: /lib/systemd/system/docker.service
    mode: '0644'
  tags:
    - level1_host
    - scored
    - rule_3.2

- name: "| 3.3 | Ensure that the docker.socket file ownership is root:root | Scored"
  file: 
    path: /lib/systemd/system/docker.socket
    owner: root
    group: root
  tags:
    - level1_host
    - scored
    - rule_3.3

- name: "| 3.4 | Ensure that docker.socket file permissions are set to 644 | Scored"
  file: 
    path: /lib/systemd/system/docker.socket
    mode: '0644'
  tags:
    - level1_host
    - scored
    - rule_3.4

- name: "| 3.5 | Ensure that the /etc/docker directory ownership is root:root | Scored"
  file: 
    path: /etc/docker
    owner: root
    group: root
  tags:
    - level1_host
    - scored
    - rule_3.5

- name: "| 3.6 | Ensure that /etc/docker directory permissions are set to 755 | Scored"
  file: 
    path: /etc/docker
    mode: '0755'
  tags:
    - level1_host
    - scored
    - rule_3.6

- name: "| 3.7 | Ensure that registry certificate ownership is root:root | Scored"
  file: 
    path: /etc/docker/certs.d/{{ registry_server }}/ca.crt
    owner: root
    group: root
  when: registry_server is defined
  tags:
    - level1_host
    - scored
    - rule_3.7

- name: "| 3.8 | Ensure that registry certificate file permissions are set to 444 | Scored"
  file: 
    path: /etc/docker/certs.d/{{ registry_server }}/ca.crt
    mode: '0444'
  when: registry_server is defined
  tags:
    - level1_host
    - scored
    - rule_3.8

- name: Check socket status
  stat:
    path: /var/run/docker.sock
  register: dock_sock

- name: "| 3.15 | Ensure that the Docker socket file ownership is root:docker | Scored"
  file: 
    path: /var/run/docker.sock
    owner: root
    group: docker
  when: dock_sock.stat.exists
  tags:
    - level1_host
    - scored
    - rule_3.15

- name: "| 3.16 | Ensure that the Docker socket file permissions are set to 660 | Scored"
  file: 
    path: /var/run/docker.sock
    mode: '0660'
  when: dock_sock.stat.exists 
  tags:
    - level1_host
    - scored
    - rule_3.16

- name: "| 3.17 | Ensure that the daemon.json file ownership is root:root | Scored"
  file: 
    path: /etc/docker/daemon.json
    owner: root
    group: root
  tags:
    - level1_host
    - scored
    - rule_3.17

- name: "| 3.18 | Ensure that the daemon.json file permissions are set to 644 | Scored"
  file: 
    path: /etc/docker/daemon.json
    mode: '0644'
  tags:
    - level1_host
    - scored
    - rule_3.18

- name: "| 3.19 | Ensure that the /etc/default/docker file ownership is root:root | Scored"
  file: 
    path: /etc/default/docker
    owner: root
    group: root
  tags:
    - level1_host
    - scored
    - rule_3.19

- name: "| 3.20 | Ensure that the /etc/sysconfig/docker file permissions s root:root | Scored"
  file: 
    path: /etc/sysconfig/docker
    owner: root
    group: root
  when: ansible_distribution == 'OracleLinux'
  tags:
    - level1_host
    - scored
    - rule_3.20

- name: "| 3.21 | Ensure that the /etc/sysconfig/docker file permissions are set to 644 | Scored"
  file: 
    path: /etc/sysconfig/docker
    mode: '0644'
  when: ansible_distribution == 'OracleLinux'
  tags:
    - level1_host
    - scored
    - rule_3.21

- name: "| 3.22 | Ensure that the /etc/default/docker file permissions are set to 644 | Scored"
  file: 
    path: /etc/default/docker
    mode: '0644'
  tags:
    - level1_host
    - scored
    - rule_3.22