---
# Hardening section for Docker on Ubuntu 18.04
- name: "| 2.1 | Ensure network traffic is restricted between containers on the default bridge | Scored \n
         | 2.2 | Ensure the logging level is set to 'info' | Scored \n
         | 2.3 | Ensure Docker is allowed to make changes to iptables | Scored \n
         | 2.4 | Ensure insecure registries are not used | Scored \n
         | 2.8 | Enable user namespace support | Scored \n
         | 2.13 | Ensure live restore is Enabled | Scored \n
         | 2.14 | Ensure Userland Proxy is Disabled | Scored \n
         | 2.17 | Ensure containers are restricted from acquiring new privileges | Scored "
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
  register: hardening
  tags:
    - level1_docker
    - scored
    - rule_2.1



#2.8 user namespaces
- name: "| 2.16 | Ensure experimental features are avoided in production | Scored "
  command: "{{ cis_rule_2_16 }}"
  register: docker_experimental_status
  changed_when: no
  check_mode: no
  failed_when: docker_experimental_status.stdout == "true"