---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: ansible-role-docker-overlay

  post_tasks:
    - name: Start the Docker daemon 
      service:
        name: docker
        state: started
