---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: ubuntu
    image: pipseed/docker-bionic-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      deprecation_warnings: false

verifier:
  name: ansible
